function showcase(){var U='',R=' top: -1000px;',pb='" for "gwt:onLoadErrorFn"',nb='" for "gwt:onPropertyErrorFn"',$='");',qb='#',Nc='.cache.js',sb='/',yb='//',cc='064B2E8184B5EB928BFE85E376A25BBD',dc='0A1191C41C08946EFE87C924E2BA3F3D',ec='184216AA39B797ACD8EE7FB943E5B15D',fc='1E3FA1129D403FCE1D349097435DCAAF',gc='1E438238206E89B2C7C1A03BEAB59CF8',hc='261D0899765967B9797FCB5F7ACF3282',ic='2817BC1E029B52BBBF122C9D356E6709',jc='3ADE5E3980C0F76416B343F956705348',kc='3FF9BFD194D1B2DFC7F3B45AE7D04572',lc='45B4E9A319A726E1AB51AD181D422069',mc='45F23A4A52C91023E1BAFD23490BDE5E',nc='4ABF6DC360F76F52A2116A44EBF14342',oc='557175F684D5D91C9D007C2C56E5ADF0',pc='5BB7AA307F895FDF10C2632DE4AF4A21',qc='68FB2426381C151709EAC055063D519A',rc='6AE1A753C9BC381F5B79EBB928AA27ED',sc='73F43DAD28BD886A7EE36129F43A2B54',tc='77783108E4E4CBCB8B9F8965338F7804',uc='7CA47076866B64BF108B85AACD0DABFC',vc='7D203B4B3585889AC082CA21630785DF',wc='7D44737AB9AF76C87B7DCEF3E218E9A1',xc='840B7EFE516D47D727E128ED99006132',yc='8CA2A54D86EE7C3383AC47EEA4E15D7C',zc='9E42F04C5F200670DF537514C3B9DD48',Mc=':',hb='::',T='<!doctype html>',V='<html><head><\/head><body><\/body><\/html>',kb='=',rb='?',Ac='AA487185EC11E0F253915B1304C569C1',Bc='BB5A2D813401BF622DF912A940F5C978',Cc='BD0F9E73D14FEBBCC00C27015BDDBE64',mb='Bad handler "',Dc='C0C1A07622D1498CD976BD06F70BEAA5',Ec='C7DAA2E0250829641DD3917ECF35AF78',Fc='CCCD355EC2089C3D5F2D22E6764C5046',Gc='CFA772D55BD338C2EF76B5906B4C8500',S='CSS1Compat',Y='Chrome',Hc='D4E79DAD0CD0DB44C51EFC4FDCE67595',X='DOMContentLoaded',M='DUMMY',Ic='EA14BEEBE462EC1B0C671C5A368C6364',Jc='EA6D5D98C540EA5D27932C80DA0E4C1D',Kc='EB9314346386D222CFF6CE9ADE99F442',Lc='F1247E98F3DC6184C66B95307CDCF8E6',Ab='android',Cb='android_tablet',xb='base',vb='baseUrl',H='begin',Ib='blackberry',N='body',G='bootstrap',ub='clear.cache.gif',jb='content',Jb='desktop',Pc='end',Z='eval("',Ob='file://',Zb='gecko',$b='gecko1_8',I='gwt.codesvr.showcase=',J='gwt.codesvr=',ob='gwt:onLoadErrorFn',lb='gwt:onPropertyErrorFn',ib='gwt:property',db='head',Yb='ie6',Xb='ie8',Wb='ie9',O='iframe',tb='img',Db='ipad',Eb='ipad_retina',Fb='iphone',Gb='ipod',ab='javascript',P='javascript:""',Oc='loadExternalRefs',eb='meta',zb='mgwt.os',Bb='mobile',Kb='mobile.user.agent',Lb='mobilesafari',cb='moduleRequested',bb='moduleStartup',Vb='msie',fb='name',Qb='no',Mb='not_mobile',Sb='opera',Nb='phonegap.env',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Hb='retina',Ub='safari',_='script',ac='selectingPermutation',K='showcase',bc='showcase.devmode.js',wb='showcase.nocache.js',gb='showcase::',L='startup',W='undefined',_b='unknown',Rb='user.agent',Tb='webkit',Pb='yes';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
showcase.__sendStats=r;showcase.__moduleName=K;showcase.__errFn=null;showcase.__moduleBase=M;showcase.__softPermutationId=0;showcase.__computePropValue=null;showcase.__getPropMap=null;showcase.__gwtInstallCode=function(){};showcase.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==S?T:U;v.write(b+V);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(_);g.language=ab;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(_);g.language=ab;g.text=c[i];e.appendChild(g);d(e,g)}}}
showcase.onScriptDownloaded=function(a){l(function(){m(a)})};r(bb,cb);var n=p.createElement(_);n.src=k;p.getElementsByTagName(db)[0].appendChild(n)}
showcase.__startLoadingFragment=function(a){return C(a)};showcase.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(_);c.language=ab;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(eb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(fb),k;if(j){j=j.replace(gb,U);if(j.indexOf(hb)>=0){continue}if(j==ib){k=i.getAttribute(jb);if(k){var l,m=k.indexOf(kb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=U}c[j]=l}}else if(j==lb){k=i.getAttribute(jb);if(k){try{d=eval(k)}catch(a){alert(mb+k+nb)}}}else if(j==ob){k=i.getAttribute(jb);if(k){try{e=eval(k)}catch(a){alert(mb+k+pb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;showcase.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(qb);if(b==-1){b=a.length}var c=a.indexOf(rb);if(c==-1){c=a.length}var d=a.lastIndexOf(sb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(tb);b.src=a+ub;a=e(b.src)}return a}
function g(){var a=t(vb);if(a!=null){return a}return U}
function h(){var a=p.getElementsByTagName(_);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(wb)!=-1){return e(a[b].src)}}return U}
function i(){var a=p.getElementsByTagName(xb);if(a.length>0){return a[a.length-1].href}return U}
function j(){var a=p.location;return a.href==a.protocol+yb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==U){k=h()}if(k==U){k=i()}if(k==U&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return showcase.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[zb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Ab)!=-1){if(a.indexOf(Bb)!=-1){return Ab}else{return Cb}}if(a.indexOf(Db)!=-1){if(window.devicePixelRatio>=2){return Eb}return Db}if(a.indexOf(Fb)!=-1||a.indexOf(Gb)!=-1){if(window.devicePixelRatio>=2){return Hb}return Fb}if(a.indexOf(Ib)!=-1){return Ib}return Jb}();return b}};i[zb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};j[Kb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Lb:Mb};i[Kb]={mobilesafari:0,not_mobile:1};j[Nb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Ab)!=-1||(a.indexOf(Db)!=-1||(a.indexOf(Gb)!=-1||(a.indexOf(Fb)!=-1||a.indexOf(Ib)!=-1)))){var b=document.location.href;if(b.indexOf(Ob)===0){return Pb}}return Qb}};i[Nb]={no:0,yes:1};j[Rb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Sb)!=-1}())return Sb;if(function(){return b.indexOf(Tb)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=9}())return Wb;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=8}())return Xb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Yb;if(function(){return b.indexOf(Zb)!=-1}())return $b;return _b};i[Rb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};showcase.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};showcase.__computePropValue=k;o.__gwt_activeModules[K].bindings=showcase.__getPropMap;r(G,ac);if(q()){return C(bc)}var l;try{h([Jb,Mb,Qb,$b],cc);h([Cb,Mb,Pb,Ub],dc);h([Ib,Lb,Qb,Ub],ec);h([Hb,Lb,Qb,Ub],fc);h([Db,Lb,Pb,Ub],gc);h([Ib,Mb,Pb,Ub],hc);h([Db,Mb,Qb,Ub],ic);h([Fb,Lb,Qb,Ub],jc);h([Fb,Lb,Pb,Ub],kc);h([Ab,Lb,Qb,Ub],lc);h([Eb,Mb,Pb,Ub],mc);h([Jb,Lb,Pb,Ub],nc);h([Cb,Lb,Pb,Ub],oc);h([Db,Lb,Qb,Ub],pc);h([Jb,Mb,Qb,Xb],qc);h([Ib,Mb,Qb,Ub],rc);h([Db,Mb,Pb,Ub],sc);h([Eb,Lb,Pb,Ub],tc);h([Hb,Lb,Pb,Ub],uc);h([Fb,Mb,Pb,Ub],vc);h([Hb,Mb,Qb,Ub],wc);h([Ab,Mb,Pb,Ub],xc);h([Jb,Mb,Pb,Ub],yc);h([Ib,Lb,Pb,Ub],zc);h([Hb,Mb,Pb,Ub],Ac);h([Jb,Mb,Qb,Ub],Bc);h([Ab,Mb,Qb,Ub],Cc);h([Fb,Mb,Qb,Ub],Dc);h([Jb,Mb,Qb,Sb],Ec);h([Jb,Lb,Qb,Ub],Fc);h([Jb,Mb,Qb,Wb],Gc);h([Cb,Lb,Qb,Ub],Hc);h([Cb,Mb,Qb,Ub],Ic);h([Eb,Lb,Qb,Ub],Jc);h([Eb,Mb,Qb,Ub],Kc);h([Ab,Lb,Pb,Ub],Lc);l=f[k(zb)][k(Kb)][k(Nb)][k(Rb)];var m=l.indexOf(Mc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}showcase.__softPermutationId=g;return C(l+Nc)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Oc,H);r(Oc,Pc)}
A();showcase.__moduleBase=B();u[K].moduleBase=showcase.__moduleBase;var F=D();E();r(G,Pc);z(F);return true}
showcase.succeeded=showcase();