function showcase(){var U='',R=' top: -1000px;',pb='" for "gwt:onLoadErrorFn"',nb='" for "gwt:onPropertyErrorFn"',$='");',qb='#',Nc='.cache.js',sb='/',yb='//',cc='0657FD26D840E7A3D42C8E939BB04F5A',dc='0B0931B77464926BE6AD8B7C32FD3361',ec='0B5CC0AAFBED1A8AA3D7A8675FF2856A',fc='0C3EE3FF3C336FA10E9ED0872B0E5FC6',gc='1227857F3EC3F94B3C362BC8C3B156DF',hc='14DE0A7D50D901F23DBE235A4EE46C82',ic='19BAD79A131CE96CD6E4AD97D0A98946',jc='2588EEAA53AC3C2459584B355B80DD2B',kc='28998FF4E31EF1C7BDBA3AFDB75BCC57',lc='29111911EC7769AD3063C70882BC8CB5',mc='2EFB598C557E7D251E166EFE5936A62D',nc='32D6BAFFEFB2065F08A82D26640BE71B',oc='3D6DD89AA9C91BCE20D133EA8FA5D43B',pc='3E879880DAD953457A751F969741233B',qc='4E59D04550E811C145FE8CF34EF25541',rc='56B4F19D9744C35EFDAF503D87D9F7FA',sc='5A3F0E3383FF7C5D53DBB623229B15E3',tc='675F8CB7055E1455835DD1EFBF27B5F2',uc='6B5D234D966F13A6507CD54921A387B1',vc='7525D96A05E61D09864161046979B5D2',wc='7CAB37526CB09E7B6006772D31B6B05A',xc='7D541036DC2174363297F9F37E9CC5DB',yc='7DBBD8FC52761018D24B9E381E7B6277',zc='80CCC3734B83F1423D8BA909F4D01EED',Ac='8F197F5D79C911C79EC318C306771B5C',Mc=':',hb='::',T='<!doctype html>',V='<html><head><\/head><body><\/body><\/html>',kb='=',rb='?',Bc='A906C8256C06C56736CF9E1FF4F95EB2',Cc='A9999AB678D2BBED9A77CA1E59C3A35B',Dc='AE07F5BA99FDEE1B84D77934824D7726',mb='Bad handler "',Ec='C81CDABFAA54E7F3733552C5CDD6FF3D',Fc='CBE2B6E7232ABBE8F26A6F79E9BDED95',Gc='CEB07BEFF491B45D9325A7DD5442E537',S='CSS1Compat',Y='Chrome',Hc='D2F56D9C02CD59EB8FEF53776C5F4B0D',Ic='DFBA67EB4DB1386BA8D6F8DE94ED35EA',X='DOMContentLoaded',M='DUMMY',Jc='E890260509D9DCB4B4ABBF5A9D8E3F63',Kc='ED36CE217531BF976E6102B9C36AC0D0',Lc='FA2E038144F766AE83CFF80EB136EC61',Ab='android',Cb='android_tablet',xb='base',vb='baseUrl',H='begin',Ib='blackberry',N='body',G='bootstrap',ub='clear.cache.gif',jb='content',Jb='desktop',Pc='end',Z='eval("',Ob='file://',Zb='gecko',$b='gecko1_8',I='gwt.codesvr.showcase=',J='gwt.codesvr=',ob='gwt:onLoadErrorFn',lb='gwt:onPropertyErrorFn',ib='gwt:property',db='head',Yb='ie6',Xb='ie8',Wb='ie9',O='iframe',tb='img',Db='ipad',Eb='ipad_retina',Fb='iphone',Gb='ipod',ab='javascript',P='javascript:""',Oc='loadExternalRefs',eb='meta',zb='mgwt.os',Bb='mobile',Kb='mobile.user.agent',Lb='mobilesafari',cb='moduleRequested',bb='moduleStartup',Vb='msie',fb='name',Qb='no',Mb='not_mobile',Sb='opera',Nb='phonegap.env',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Hb='retina',Ub='safari',_='script',ac='selectingPermutation',K='showcase',bc='showcase.devmode.js',wb='showcase.nocache.js',gb='showcase::',L='startup',W='undefined',_b='unknown',Rb='user.agent',Tb='webkit',Pb='yes';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
showcase.__sendStats=r;showcase.__moduleName=K;showcase.__errFn=null;showcase.__moduleBase=M;showcase.__softPermutationId=0;showcase.__computePropValue=null;showcase.__getPropMap=null;showcase.__gwtInstallCode=function(){};showcase.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==S?T:U;v.write(b+V);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(_);g.language=ab;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(_);g.language=ab;g.text=c[i];e.appendChild(g);d(e,g)}}}
showcase.onScriptDownloaded=function(a){l(function(){m(a)})};r(bb,cb);var n=p.createElement(_);n.src=k;p.getElementsByTagName(db)[0].appendChild(n)}
showcase.__startLoadingFragment=function(a){return C(a)};showcase.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(_);c.language=ab;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(eb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(fb),k;if(j){j=j.replace(gb,U);if(j.indexOf(hb)>=0){continue}if(j==ib){k=i.getAttribute(jb);if(k){var l,m=k.indexOf(kb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=U}c[j]=l}}else if(j==lb){k=i.getAttribute(jb);if(k){try{d=eval(k)}catch(a){alert(mb+k+nb)}}}else if(j==ob){k=i.getAttribute(jb);if(k){try{e=eval(k)}catch(a){alert(mb+k+pb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;showcase.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(qb);if(b==-1){b=a.length}var c=a.indexOf(rb);if(c==-1){c=a.length}var d=a.lastIndexOf(sb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(tb);b.src=a+ub;a=e(b.src)}return a}
function g(){var a=t(vb);if(a!=null){return a}return U}
function h(){var a=p.getElementsByTagName(_);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(wb)!=-1){return e(a[b].src)}}return U}
function i(){var a=p.getElementsByTagName(xb);if(a.length>0){return a[a.length-1].href}return U}
function j(){var a=p.location;return a.href==a.protocol+yb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==U){k=h()}if(k==U){k=i()}if(k==U&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return showcase.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[zb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Ab)!=-1){if(a.indexOf(Bb)!=-1){return Ab}else{return Cb}}if(a.indexOf(Db)!=-1){if(window.devicePixelRatio>=2){return Eb}return Db}if(a.indexOf(Fb)!=-1||a.indexOf(Gb)!=-1){if(window.devicePixelRatio>=2){return Hb}return Fb}if(a.indexOf(Ib)!=-1){return Ib}return Jb}();return b}};i[zb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};j[Kb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Lb:Mb};i[Kb]={mobilesafari:0,not_mobile:1};j[Nb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Ab)!=-1||(a.indexOf(Db)!=-1||(a.indexOf(Gb)!=-1||(a.indexOf(Fb)!=-1||a.indexOf(Ib)!=-1)))){var b=document.location.href;if(b.indexOf(Ob)===0){return Pb}}return Qb}};i[Nb]={no:0,yes:1};j[Rb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Sb)!=-1}())return Sb;if(function(){return b.indexOf(Tb)!=-1}())return Ub;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=9}())return Wb;if(function(){return b.indexOf(Vb)!=-1&&p.documentMode>=8}())return Xb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Yb;if(function(){return b.indexOf(Zb)!=-1}())return $b;return _b};i[Rb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};showcase.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};showcase.__computePropValue=k;o.__gwt_activeModules[K].bindings=showcase.__getPropMap;r(G,ac);if(q()){return C(bc)}var l;try{h([Hb,Mb,Qb,Ub],cc);h([Hb,Lb,Qb,Ub],dc);h([Jb,Lb,Qb,Ub],ec);h([Cb,Lb,Qb,Ub],fc);h([Ab,Mb,Qb,Ub],gc);h([Ab,Lb,Pb,Ub],hc);h([Db,Lb,Qb,Ub],ic);h([Jb,Mb,Qb,Wb],jc);h([Ib,Lb,Pb,Ub],kc);h([Hb,Lb,Pb,Ub],lc);h([Ab,Lb,Qb,Ub],mc);h([Fb,Mb,Pb,Ub],nc);h([Ib,Mb,Pb,Ub],oc);h([Jb,Mb,Pb,Ub],pc);h([Cb,Mb,Qb,Ub],qc);h([Hb,Mb,Pb,Ub],rc);h([Eb,Mb,Qb,Ub],sc);h([Cb,Lb,Pb,Ub],tc);h([Jb,Mb,Qb,Sb],uc);h([Jb,Mb,Qb,Xb],vc);h([Jb,Lb,Pb,Ub],wc);h([Ib,Mb,Qb,Ub],xc);h([Cb,Mb,Pb,Ub],yc);h([Eb,Lb,Pb,Ub],zc);h([Jb,Mb,Qb,Ub],Ac);h([Ib,Lb,Qb,Ub],Bc);h([Db,Lb,Pb,Ub],Cc);h([Jb,Mb,Qb,$b],Dc);h([Eb,Lb,Qb,Ub],Ec);h([Fb,Lb,Pb,Ub],Fc);h([Fb,Lb,Qb,Ub],Gc);h([Db,Mb,Pb,Ub],Hc);h([Ab,Mb,Pb,Ub],Ic);h([Eb,Mb,Pb,Ub],Jc);h([Fb,Mb,Qb,Ub],Kc);h([Db,Mb,Qb,Ub],Lc);l=f[k(zb)][k(Kb)][k(Nb)][k(Rb)];var m=l.indexOf(Mc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}showcase.__softPermutationId=g;return C(l+Nc)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Oc,H);r(Oc,Pc)}
A();showcase.__moduleBase=B();u[K].moduleBase=showcase.__moduleBase;var F=D();E();r(G,Pc);z(F);return true}
showcase.succeeded=showcase();