function showcase(){var fb='',R=' top: -1000px;',ob='" for "gwt:onLoadErrorFn"',mb='" for "gwt:onPropertyErrorFn"',$='");',pb='#',Mc='.cache.js',rb='/',xb='//',bc='0740CC18D879CA061FF6475DFC5DB986',cc='137882EC4C64AC490B2F3AF8F40B6AD8',dc='156CEC777F24C18ECB996E87FF083790',ec='21E51F6333D79B0C285B5850EF3C6164',fc='2B6EEB3108471B82C92C804CF55233EF',gc='360DDA48D6B90E153040A11C8717589A',hc='3DD5E57D204787DA1CA60BE0A794317D',ic='3EB9D6223059E1E815E665C0D8195C68',jc='440CEFE4049B9024B1008AB1118C64A1',kc='525F9E3E1708967B1E76F87F54B68F3F',lc='6C31A2B495560D42DE97BFDF670B15E2',mc='6F0B1065ACF41B2098165690C43EC6D9',nc='7653DD169B3D3032A0F6E33FD9746A92',oc='77165B5C0A4646B1A4423A8198CCA643',pc='889E70D5A7D7556ACE43432C9D0EFB4A',qc='8A594E111FA54EA1CCA3E7855265DDA4',rc='8D3386450B9A0A2FF5DD79EF2D612DDD',sc='8EBA0D930516A12F961362FA93C5305B',tc='8EDC682FF18719E8C674E9020923A5F8',uc='90E06D02074DCF192751FA50CE0071F5',vc='92B29D04C92E50EDB199C15E89BE3D95',wc='95EDAD8EEEF608289D8DA3C1B8AEDFD6',xc='9D8FF79C5A12FBAF838063F2E77E5CAF',Lc=':',gb='::',S='<html><head><\/head><body><\/body><\/html>',jb='=',qb='?',yc='A76E1DBABBC7E5D786D8EE92223BAAC9',zc='ADB9B66284BEC117F2B54DC320896719',Ac='AEA8B456441B6D11121B3D09F399D0A9',Bc='BD2707770254C2302E653F4A57C3BD0C',lb='Bad handler "',Cc='C93FD765E3515095C58A2876675EC084',Y='Chrome',Dc='D105F7D10DA541470A561D8D8351897F',Ec='D443B446AFAA480E42ADBBF04F220160',Fc='D673395875CB6EC5726FD86798B233F8',Gc='DBA65AC7FEF98C379A302DD67DD87ADB',X='DOMContentLoaded',M='DUMMY',Hc='F7D024FB3228F720BD180B860F948D72',Ic='F8D630283B151587B04C0552E8495B56',Jc='FA16ADD8610A64F112011F0745D678B5',Kc='FB8B264EFCC91C10E7EF672714DF4976',zb='android',Bb='android_tablet',wb='base',ub='baseUrl',H='begin',Hb='blackberry',N='body',G='bootstrap',tb='clear.cache.gif',ib='content',Ib='desktop',Oc='end',Z='eval("',Nb='file://',Yb='gecko',Zb='gecko1_8',I='gwt.codesvr.showcase=',J='gwt.codesvr=',nb='gwt:onLoadErrorFn',kb='gwt:onPropertyErrorFn',hb='gwt:property',bb='head',Xb='ie6',Wb='ie8',Vb='ie9',O='iframe',sb='img',Cb='ipad',Db='ipad_retina',Eb='iphone',Fb='ipod',U='javascript',P='javascript:""',Nc='loadExternalRefs',cb='meta',yb='mgwt.os',Ab='mobile',Jb='mobile.user.agent',Kb='mobilesafari',ab='moduleRequested',_='moduleStartup',Ub='msie',db='name',Pb='no',Lb='not_mobile',Rb='opera',Mb='phonegap.env',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Gb='retina',Tb='safari',T='script',_b='selectingPermutation',K='showcase',ac='showcase.devmode.js',vb='showcase.nocache.js',eb='showcase::',L='startup',W='undefined',$b='unknown',Qb='user.agent',V='var $wnd = window.parent;',Sb='webkit',Ob='yes';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
showcase.__sendStats=r;showcase.__moduleName=K;showcase.__errFn=null;showcase.__moduleBase=M;showcase.__softPermutationId=0;showcase.__computePropValue=null;showcase.__getPropMap=null;showcase.__gwtInstallCode=function(){};showcase.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(S);v.close();var b=v.getElementsByTagName(N)[0];var c=v.createElement(T);c.language=U;var d=V;c.text=d;b.appendChild(c)}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(T);g.language=U;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(T);g.language=U;g.text=c[i];e.appendChild(g);d(e,g)}}}
showcase.onScriptDownloaded=function(a){l(function(){m(a)})};r(_,ab);var n=p.createElement(T);n.src=k;p.getElementsByTagName(bb)[0].appendChild(n)}
showcase.__startLoadingFragment=function(a){return C(a)};showcase.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(T);c.language=U;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(cb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(db),k;if(j){j=j.replace(eb,fb);if(j.indexOf(gb)>=0){continue}if(j==hb){k=i.getAttribute(ib);if(k){var l,m=k.indexOf(jb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=fb}c[j]=l}}else if(j==kb){k=i.getAttribute(ib);if(k){try{d=eval(k)}catch(a){alert(lb+k+mb)}}}else if(j==nb){k=i.getAttribute(ib);if(k){try{e=eval(k)}catch(a){alert(lb+k+ob)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;showcase.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(pb);if(b==-1){b=a.length}var c=a.indexOf(qb);if(c==-1){c=a.length}var d=a.lastIndexOf(rb,Math.min(c,b));return d>=0?a.substring(0,d+1):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(sb);b.src=a+tb;a=e(b.src)}return a}
function g(){var a=t(ub);if(a!=null){return a}return fb}
function h(){var a=p.getElementsByTagName(T);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(vb)!=-1){return e(a[b].src)}}return fb}
function i(){var a=p.getElementsByTagName(wb);if(a.length>0){return a[a.length-1].href}return fb}
function j(){var a=p.location;return a.href==a.protocol+xb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==fb){k=h()}if(k==fb){k=i()}if(k==fb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return showcase.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[yb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(zb)!=-1){if(a.indexOf(Ab)!=-1){return zb}else{return Bb}}if(a.indexOf(Cb)!=-1){if(window.devicePixelRatio>=2){return Db}return Cb}if(a.indexOf(Eb)!=-1||a.indexOf(Fb)!=-1){if(window.devicePixelRatio>=2){return Gb}return Eb}if(a.indexOf(Hb)!=-1){return Hb}return Ib}();return b}};i[yb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};j[Jb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Kb:Lb};i[Jb]={mobilesafari:0,not_mobile:1};j[Mb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(zb)!=-1||(a.indexOf(Cb)!=-1||(a.indexOf(Fb)!=-1||(a.indexOf(Eb)!=-1||a.indexOf(Hb)!=-1)))){var b=document.location.href;if(b.indexOf(Nb)===0){return Ob}}return Pb}};i[Mb]={no:0,yes:1};j[Qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Rb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1}())return Tb;if(function(){return b.indexOf(Ub)!=-1&&p.documentMode>=9}())return Vb;if(function(){return b.indexOf(Ub)!=-1&&p.documentMode>=8}())return Wb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Xb;if(function(){return b.indexOf(Yb)!=-1}())return Zb;return $b};i[Qb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};showcase.__getPropMap=function(){var a={};for(var b in i){a[b]=k(b)}return a};showcase.__computePropValue=k;o.__gwt_activeModules[K].bindings=showcase.__getPropMap;r(G,_b);if(q()){return C(ac)}var l;try{h([Hb,Kb,Ob,Tb],bc);h([Db,Lb,Ob,Tb],cc);h([Bb,Lb,Pb,Tb],dc);h([Cb,Lb,Ob,Tb],ec);h([Eb,Kb,Pb,Tb],fc);h([Ib,Lb,Pb,Vb],gc);h([Hb,Kb,Pb,Tb],hc);h([Cb,Lb,Pb,Tb],ic);h([Gb,Lb,Ob,Tb],jc);h([Eb,Lb,Pb,Tb],kc);h([zb,Kb,Pb,Tb],lc);h([Db,Kb,Pb,Tb],mc);h([zb,Kb,Ob,Tb],nc);h([Db,Lb,Pb,Tb],oc);h([zb,Lb,Ob,Tb],pc);h([Bb,Lb,Ob,Tb],qc);h([Eb,Kb,Ob,Tb],rc);h([Ib,Kb,Pb,Tb],sc);h([Ib,Kb,Ob,Tb],tc);h([Cb,Kb,Ob,Tb],uc);h([Hb,Lb,Ob,Tb],vc);h([Db,Kb,Ob,Tb],wc);h([Cb,Kb,Pb,Tb],xc);h([Bb,Kb,Ob,Tb],yc);h([Ib,Lb,Pb,Zb],zc);h([Ib,Lb,Ob,Tb],Ac);h([Gb,Kb,Pb,Tb],Bc);h([zb,Lb,Pb,Tb],Cc);h([Bb,Kb,Pb,Tb],Dc);h([Eb,Lb,Ob,Tb],Ec);h([Hb,Lb,Pb,Tb],Fc);h([Gb,Kb,Ob,Tb],Gc);h([Gb,Lb,Pb,Tb],Hc);h([Ib,Lb,Pb,Tb],Ic);h([Ib,Lb,Pb,Rb],Jc);h([Ib,Lb,Pb,Wb],Kc);l=f[k(yb)][k(Jb)][k(Mb)][k(Qb)];var m=l.indexOf(Lc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}showcase.__softPermutationId=g;return C(l+Mc)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Nc,H);r(Nc,Oc)}
A();showcase.__moduleBase=B();u[K].moduleBase=showcase.__moduleBase;var F=D();E();r(G,Oc);z(F);return true}
showcase.succeeded=showcase();